# Generated by Django 5.1.4 on 2025-01-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.TextField(blank=True, help_text="User's address", null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, help_text="User's email address", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_url',
            field=models.URLField(default=None, help_text='URL to the uploaded resume file', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True, help_text="User's LinkedIn profile URL", max_length=500, null=True),
        ),
    ]
