# Generated by Django 5.1.4 on 2025-01-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_job_job_posted_at_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file_url',
            field=models.URLField(blank=True, help_text='URL to the uploaded resume file', max_length=500, null=True),
        ),
    ]
