# Generated by Django 5.1.4 on 2025-09-18 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_resume_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer_logo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer_website',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_apply_is_direct',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_employment_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_google_link',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_id_from_source',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_max_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_min_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_state',
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_html',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_last_checked',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_tags',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_apply_link',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_benefits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_employment_types',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_qualifications',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_responsibilities',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
