# Generated by Django 5.1.4 on 2025-09-18 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_company_remove_job_employer_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=500)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_logo', models.URLField(blank=True, max_length=500, null=True)),
                ('company_website', models.URLField(blank=True, max_length=500, null=True)),
                ('platform', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
