# Generated by Django 5.1.4 on 2025-10-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_html',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
