# Generated by Django 5.1.4 on 2025-10-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_job_job_html_alter_job_job_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profession',
            field=models.CharField(default=None, help_text='Users profession', max_length=255),
            preserve_default=False,
        ),
    ]
