# Generated by Django 5.1.4 on 2025-10-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_resume_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='personal_information',
            field=models.JSONField(default=list, help_text='List of personal information strings (name, email, phone, address, linkedin, website)'),
        ),
    ]
