# Generated by Django 5.1.4 on 2025-10-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_personal_information_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='personal_information',
            field=models.JSONField(default=list, help_text="List of personal information dictionaries with 'field' and 'value' keys"),
        ),
    ]
