# Generated by Django 5.1.4 on 2025-10-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_resume_address_remove_resume_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='text',
        ),
    ]
