# Generated by Django 5.1.4 on 2025-10-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_resume_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='profession',
        ),
    ]
