# Generated by Django 5.1.4 on 2025-10-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_resume_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='awards',
            field=models.JSONField(default=list, help_text="List of user's awards"),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.JSONField(default=list, help_text="List of user's certificate"),
        ),
    ]
