# Generated by Django 5.1.4 on 2025-10-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_resume_awards_resume_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='awards',
            field=models.JSONField(blank=True, default=list, help_text="List of user's awards", null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text="List of user's certificate", null=True),
        ),
    ]
