# Generated by Django 5.1.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='uncategorized_skills',
        ),
    ]
