# Generated by Django 5.1.4 on 2026-02-10 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_uncategorized_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(default=list, help_text="List of user's skills categorized by type. Each item should have 'category' and 'skills' keys"),
        ),
        migrations.CreateModel(
            name='UserOutreach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outreach_type', models.CharField(choices=[('INCOMPLETE_PROFILE', 'Incomplete Profile'), ('NO_APPLICATION', 'No Application'), ('NO_JOB_SEARCH', 'No Job Search')], help_text='Type of outreach sent', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the outreach was sent')),
                ('user', models.ForeignKey(help_text='User who received the outreach', on_delete=django.db.models.deletion.CASCADE, related_name='outreach_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('user', 'outreach_type')},
            },
        ),
    ]
