# Generated by Django 5.2.4 on 2025-07-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_tag',
            new_name='job_tags',
        ),
    ]
