# Generated by Django 5.2.4 on 2025-07-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_job_tag_job_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_country',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_employment_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contractor', 'Contractor'), ('contract', 'Contract')], default='full-time', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
