# Generated by Django 5.2.4 on 2025-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_job_job_country_alter_job_job_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
