# Generated by Django 5.1.4 on 2025-01-18 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_resume_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_posted_at_timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
