# Generated by Django 5.2.4 on 2025-07-16 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_job_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='platform',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_apply_link',
            field=models.URLField(max_length=500, unique=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
