# Generated by Django 5.2.4 on 2025-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_company_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_employment_type',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
