# Generated by Django 5.1.4 on 2025-03-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_job_is_active_job_job_apply_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id_from_source',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
