# Generated by Django 5.2.4 on 2025-08-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_job_job_employment_type_and_more'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='job',
        #    name='job_country',
        #),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.JSONField(default=dict),
        ),
    ]
