# Generated by Django 5.1.4 on 2025-03-26 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_job_job_id_from_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_google_link',
            field=models.URLField(blank=True, max_length=1000, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
